package constants

type ChainName string

const (
	ChainNameETH      ChainName = "ETH"
	ChainNameSOLANA   ChainName = "SOLANA"
	ChainNameARB      ChainName = "ARB"
	ChainNameAVAX     ChainName = "AVAX"
	ChainNameBSC      ChainName = "BSC"
	ChainNameBTC      ChainName = "BTC"
	ChainNameBCH      ChainName = "BCH"
	ChainNameSMARTBCH ChainName = "SMARTBCH"
	ChainNameKLAY     ChainName = "KLAY"
	ChainNameBTMC     ChainName = "BTMC"
	ChainNameBTM      ChainName = "BTM"
	ChainNameCARDANO  ChainName = "CARDANO"
	ChainNameOPTIMISM ChainName = "OPTIMISM"
	ChainNameDASH     ChainName = "DASH"
	ChainNameDCR      ChainName = "DCR"
	ChainNameDOGE     ChainName = "DOGE"
	ChainNameECASH    ChainName = "ECASH"
	ChainNameETC      ChainName = "ETC"
	ChainNameETF      ChainName = "ETF"
	ChainNameETHW     ChainName = "ETHW"
	ChainNameFTM      ChainName = "FTM"
	ChainNameFIL      ChainName = "FIL"
	ChainNameHECO     ChainName = "HECO"
	ChainNameKSM      ChainName = "KSM"
	ChainNameLTC      ChainName = "LTC"
	ChainNameNEAR     ChainName = "NEAR"
	ChainNameDOT      ChainName = "DOT"
	ChainNameMATIC    ChainName = "MATIC"
	ChainNameSTELLAR  ChainName = "STELLAR"
	ChainNameTRON     ChainName = "TRON"
	ChainNameTON      ChainName = "TON"
	ChainNameZEC      ChainName = "ZEC"
	ChainNameXRP      ChainName = "XRP"
	ChainNameZKSYNC   ChainName = "ZKSYNC"
)
